### ISSUE TITLE
想要做海报生成之前显示加载中的效果

### ISSUE THREAD

**Issue by littleBelle** [MyQuitter/uni-app-components#3]
感谢作者，用你写的组件已经基本完成了海报的生成，但是还有一个功能我不知道怎么实现：
  第一次生成海报，海报生成之前，显示加载中showLoading，生成之后hideLoading，第二次点开时，因为第一次已经生成了，就不需要显示加载中了，这个显示加载中的方法我应该放在哪里，或者我要怎么去判断，是否之前已经生成过海报，不需要加载中了，麻烦教我一下，谢谢大神

**Comment by MyQuitter** [comment]
方法有很多种，给你提供下我的想法
1.存个状态值来进行控制是否显示加载
2.存生成出来的海报图片
